name: PolishPVP
main: io.github.adytech99.polishpvp.Main
version: 1.20.1
api-version: '1.20'
load: STARTUP
commands:
  stats:
    description: Opens the statistics
    aliases:
      - statistics
      - s
      - kills
      - deaths

  resetstats:
    description: Permanently resets your statistics. Be careful!

  kit:
    description: Gives the default kit (diamond)
    aliases:
      - suit-up

